---

- hosts: db
# host is to define the name of your host machine, group or all servers
# in this example we are targeting server called web
  gather_facts: yes
# gethering facts before performing any tasks
  become: true
# become is used to get root permission to perform any tasks that may require admin access
  tasks:
    # - name: Install wget
    #   yum:
    #     name: wget
    #     state: present

    - name: MongoDB - Import public key
      shell: wget -qO - https://www.mongodb.org/static/pgp/server-3.2.asc | sudo apt-key add -

    #
    # - name: Import the public key used by the package management system
    #   apt_key:
    #     keyserver: hkp://keyserver.ubuntu.com:80
    #     id: EA312927

    - name: Import the public key used by the package management system
      apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10 state=present
    # - name: Add MongoDB repository
    #   apt_repository: repo='deb <a class="vglnk" href="http://downloads-distro.mongodb.org/repo/ubuntu-upstart" rel="nofollow"><span>http</span><span>://</span><span>downloads</span><span>-</span><span>distro</span><span>.</span><span>mongodb</span><span>.</span><span>org</span><span>/</span><span>repo</span><span>/</span><span>ubuntu</span><span>-</span><span>upstart</span></a> dist 10gen' state=present

    - name: Add MongoDB repository
      apt_repository:
        # repo: 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'
        filename: '/etc/apt/sources.list.d/mongodb-org-3.2.list'
        repo: 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'
        state: present
        update_cache: yes



    # - name: MongoDB - Install MongoDB
    #   apt:
    #     name: mongodb-org
    #     state: present
    #     update_cache: yes

    - name: install mongodb
      apt:
        pkg: mongodb-org
        state: latest
        update_cache: yes
      notify:
        - start mongodb

  handlers:
    - name: start mongodb
      service: name=mongod state=started
